# Generated by Django 6.0 on 2026-02-01 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_authentication', '0001_initial'),
        ('mod_volunteering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteertask',
            name='assigned_volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mod_authentication.volunteer'),
        ),
        migrations.CreateModel(
            name='OrgInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_authentication.institution')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_authentication.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='mod_authentication.institution')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_authentication.volunteer')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='mod_volunteering.volunteercampaign')),
            ],
        ),
        migrations.AddField(
            model_name='volunteertask',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='mod_volunteering.volunteercampaign'),
        ),
        migrations.DeleteModel(
            name='TaskApplication',
        ),
    ]
