# Generated by Django 6.0 on 2026-02-27 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_donations', '0002_remove_donationcampaign_current_amount'),
        ('mod_volunteering', '0002_volunteertask_assigned_volunteer_orginvitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteercampaign',
            name='donation_campaign',
            field=models.ForeignKey(help_text='Volunteer campaigns must be associated with a donation campaign.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_campaigns', to='mod_donations.donationcampaign'),
        ),
    ]
