# Generated by Django 6.0 on 2026-03-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_donations', '0002_remove_donationcampaign_current_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcampaign',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='location_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='donationrecord',
            name='current_location',
            field=models.CharField(blank=True, help_text='Current city or hub', max_length=255),
        ),
        migrations.AddField(
            model_name='donationrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Pickup'), ('shipped', 'In Transit'), ('received', 'Received')], default='pending', max_length=20),
        ),
    ]
