# Generated by Django 6.0 on 2026-03-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_donations', '0003_donationcampaign_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrecord',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='donationrecord',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='donationrecord',
            name='current_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='donationrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('collected', 'Item Collected'), ('transit', 'Item in Transit'), ('received', 'Item Received at Institution'), ('delivered', 'Item Delivered')], default='pending', max_length=20),
        ),
    ]
