# Generated by Django 6.0 on 2026-03-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_donations', '0004_donationrecord_latitude_donationrecord_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('collected', 'Item Collected'), ('transit', 'Item in Transit'), ('reached', 'Reached Institution'), ('received', 'Item Received at Institution'), ('delivered', 'Item Delivered')], default='pending', max_length=20),
        ),
    ]
