# Generated by Django 6.0 on 2026-02-14 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod_authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='donation_amount',
        ),
    ]
